dragging = false;
fix = physics_fixture_create();
physics_fixture_set_box_shape(fix,16,16);
physics_fixture_set_density(fix,0.225);
physics_fixture_set_restitution(fix,0);
physics_fixture_set_collision_group(fix,1);
physics_fixture_set_linear_damping(fix,0);
physics_fixture_set_angular_damping(fix,0);
physics_fixture_set_friction(fix,0);
physics_fixture_set_awake(fix,true);
physics_fixture_bind(fix,id);
xprev = phy_position_x;
yprev = phy_position_y;